import{a as B,i as a,S as w}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const C="https://pixabay.com/api/",S="33135653-4734ab6feb6e20c316e4b7aea";async function u(o,t){try{return(await B.get(C,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:!0}})).data}catch{return a.error({message:"Error fetching data. Please try again later.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"}),{hits:[],totalHits:0}}}const v=new w(".gallery a",{captionsData:"alt"}),F=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".btnMore");function f(o){const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:n,comments:b,downloads:L})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}" >
        <img src="${s}" alt="${e}">
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${L}</p>
      </div>
    </li>
  `).join("");F.insertAdjacentHTML("beforeend",t),v.refresh()}function P(){F.innerHTML=""}function q(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}function h(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}function y(){g.classList.add("hidden")}function p(){g.classList.remove("hidden")}const M=document.querySelector(".form"),$=document.querySelector(".btnMore");let c="",i=1;d();M.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.search.value.trim(),!c){a.error({message:"Please enter a search term!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"});return}i=1,h(),y(),P();try{const{hits:t,totalHits:s}=await u(c,i);if(s===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"});return}f(t),s>i*15?p():a.info({message:"We're sorry, but you've reached the end of search results.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#1B6CB5",position:"topRight"})}catch{a.error({message:"Something went wrong. Please try again."})}finally{d()}});$.addEventListener("click",async()=>{y(),h(),i+=1;try{const{hits:o,totalHits:t}=await u(c,i);f(o),i*15<t?p():a.info({message:"We're sorry, but you've reached the end of search results.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#1B6CB5",position:"topRight"}),q()}catch{a.error({message:"Something went wrong. Please try again."})}finally{d()}});
//# sourceMappingURL=index.js.map
